### ISSUE TITLE
Create a hierarchy from a list of lists

### ISSUE THREAD

**Issue by alphapapa** [DamienCassou/hierarchy#23]
From https://github.com/melpa/melpa/pull/4704#issuecomment-294224591

> I guess I'm just a novice, but I don't understand the parentfn API for building the hierarchy. It seems like an awkward way of passing the same information that a simple list of lists would have. I'm assuming there's an academic or theoretical basis that is way over my head, but not knowing that makes it hard for me to understand how and when I would use this library. This is just FYI, not a complaint. :)

**Comment by DamienCassou** [comment]
Thank you for your remark. Building a hierarchy with `parentfn`/`childrenfn` can be convenient to avoid building a list structure only to create a hierarchy. Have a look at how I use hierarchy to build [a file hierarchy](https://github.com/DamienCassou/hierarchy/blob/master/examples/hierarchy-examples-fs.el#L44) and [a class hierarchy](https://github.com/DamienCassou/klassified.el/blob/master/klassified.el).

Moreover, I'm not saying what I implemented is the only way and we could add other ways to build a hierarchy, for example from a list of lists. Would you mind sending a PR implementing that?

**Comment by alphapapa** [comment]
Sorry if I've given the wrong impression here.  I don't mean this as a complaint or request that you do anything.  I just meant to offer an observation from the perspective of an average (?) Emacs/elisp user trying to figure out if this would be useful for me.  :)

**Comment by DamienCassou** [comment]
You didn't give the wrong impression at all (sorry if I did :-)). I agree with you there could be other ways to create a hierarchy and would welcome them in the code base. Would you mind trying to implement your idea? What kind of list structure do you have in mind to represent the following?

```
animal
  bird
    dove
    pigeon
  cow
  dolphin
```

**Comment by alphapapa** [comment]
I feel like I must be missing something, because I thought a simple list of lists would suffice, e.g.

```el
'(animal (bird (dove)
               (pigeon))
         (cow)
         (dolphin))
```

**Comment by DamienCassou** [comment]
That would be ok for me.
