### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by rhymer** [DamienCassou/hierarchy#50]
I learned about this package from Planet Emacsen; it looks really cool! I wounder if this package can handle xml files? Thanks!

**Comment by DamienCassou** [comment]
XML has a highly hierarchical structure so I'm quite sure `hierarchy` would be a good fit. Even though it's not the purpose of `hierarchy` to support XML documents, I could certainly help someone willing to implement an xml navigator package (in the same way there is a [JSON navigator](https://github.com/DamienCassou/json-navigator)).

**Comment by rhymer** [comment]
It seems to me the key is to create a function `xml-navigator--children`, similar to `json-navigator--children`, and the rest should be quite the same as `json-navigator`.

From EmacsWiki, there is a code snippet to generate tree widget from xml:
```lisp
(defun xml->tree-widget (root)
  (cond ((null root) nil)
	((listp root) (let ((elem (xml-node-name root))
			    (children (remove-if (function stringp) (xml-node-children root))))
			`(tree-widget :node (push-button
					     :tag ,(format "%s" elem)
					     :format "%[%t%]\n"
					     :xml-node ,root
					     :notify ,(lambda (widget &rest rest)
                                                        (message (format "%s" (widget-get widget :xml-node)))))
				      ,@(mapcar (lambda (x) (xml->tree-widget x)) children))))))
```

This will create a tree representation for xml very similar to `json-navigator`.
Do you have any suggestion where I can start from here? Thanks!

**Comment by DamienCassou** [comment]
Here is a prototype based on your code: https://github.com/DamienCassou/hierarchy/pull/52. Please make something out of it :-).

**Comment by rhymer** [comment]
Awesome! Thanks for the prototype!

**Comment by DamienCassou** [comment]
If you care about the topic, please start a project and make your code depend on hierarchy. If you need any help, please ask. I'm closing this issue as there it doesn't contain anything actionable for me.
