### ISSUE TITLE
Support for presenting a function call graph ?

### ISSUE THREAD

**Issue by beacoder** [DamienCassou/hierarchy#51]
I'm thinking could it be used to present a function call graph in the future ?
for example: use ggtags to generate the function call graph data, and then use hierarchy to show it ?

**Comment by DamienCassou** [comment]
I have no clue what such data would look like but if it's a hierarchy that should be possible. I can help if you want to try. What does the data look like?

**Comment by bizzyman** [comment]
Hi, I am also very interested in this feature. The feature would look something like this:

https://d3nmt5vlzunoa1.cloudfront.net/pycharm/files/2014/09/callhierarchy.png

Where each functions/class call tree would be visualised, so if you have a parent function, you could see it's children, etc

**Comment by DamienCassou** [comment]
bizzyman <notifications@github.com> writes:
> Hi, I am also very interested in this feature. The feature would 
> look something like this: 
> 
> https://d3nmt5vlzunoa1.cloudfront.net/pycharm/files/2014/09/callhierarchy.png 
> 
> Where each functions/class call tree would be visualised, so if 
> you have a parent function, you could see it's children, etc 


this seems like exactly what hierarchy has been written for. Try 
it and ask me if you need help. 

-- 
Damien Cassou
Företagsplatsen AB
Phone/Fax: +46 (0)8 774 63 00
Mobile: +33 (0)6 80 50 18 91
Address: Skeppsbron 26, 4tr, SE-111 30 Stockholm
Web: www.foretagsplatsen.se

**Comment by DamienCassou** [comment]
If you care about the topic, please start a project and make your code depend on hierarchy. If you need any help, please ask. I'm closing this issue as there it doesn't contain anything actionable for me.

**Comment by beacoder** [comment]
Just started my own, based on your hierarchy.
https://github.com/beacoder/call-graph

**Comment by DamienCassou** [comment]
Really nice! How did you find the API? Was it simple to understand and get started with? Was it powerful enough for your needs?

I'm closing this issue now.

**Comment by beacoder** [comment]
I think the naming of the api is pretty straight-forward which makes it easier for me to find the right one for my use.
yeah, it's powerful, especially when combind with the tree-mode.
also the sample on your readme helped me a lot during setting up a workable prototype.
thanks, and keep up the great work.
