### ISSUE TITLE
Org-mode file manipulation with Hierarchy

### ISSUE THREAD

**Issue by porpoiseless** [DamienCassou/hierarchy#53]
Great package! When I saw it on planet.emacsen, I began to wonder how difficult it would be to incorporate support for viewing & editing org-mode lists. I plan on reading through some org-mode code, but maybe someone who knows org's innards better than I do could throw something together quickly.

Thanks for putting together something this cool!

**Comment by andersjohansson** [comment]
Just some pointers:
- `org-element.el` is the library responsible for parsing org-buffers (especially for exports). Some documentation is here: http://orgmode.org/worg/dev/org-element-api.html. Using `org-element-map` to transform a parsed org-tree to a hierarchy might be possible, even though I suspect the org-element API itself may really be more suited for this purpose. Maybe extending it in some way with the useful tools of hierarchy would be suitable. One problem with `hierarchy.el` right now is that the entries in a hierarchy are best to keep rather simple (as they will be keys in a hash table, currently compared with `equal`, see #2), but for an org-tree you would need quite a few properties associated with each node. These properties are already defined in `org-element`.
- There is also `org-list.el` for dealing with plain lists. I haven’t looked much into it.
- I have used `hierarchy` in my org-related project, for sorting hierarchical lists of tags, and then outputting these lists as org-trees, which proved simple and nice compared to the home-grown solution I had before for dealing with this hierarchical data structure (see for example [function `orgqda--insert-hierarchical-taglist` in `orgqda.el`](https://github.com/andersjohansson/orgqda/blob/91e8cbbbf9d6ac693a1db0f060a6dfa601398698/orgqda.el#L831))

**Comment by DamienCassou** [comment]
If you care about the topic, please start a project and make your code depend on hierarchy. If you need any help, please ask. I'm closing this issue as there it doesn't contain anything actionable for me.
