### ISSUE TITLE
Add keybindings for n and p for navigation

### ISSUE THREAD

**Issue by NicolasPetton** [DamienCassou/hierarchy#58]
I would be nice (and more convenient than TAB/S-TAB IMHO) to be able to navigate with n and p.

**Comment by DamienCassou** [comment]
The target users of `hierarchy` are library authors and I expect them to have their own major mode with keybindings. The function hierarchy-tree-display is mostly a demo to show how people could render a hierarchy with a tree widget. I don't plan to give that function more responsibility for now.

If you have suggestions to improve the tree widget, you may want to ask the Emacs mailing list instead. Another solution would be to create a dedicated Emacs package. Then. `hierarchy` could use that.

**Comment by DamienCassou** [comment]
I'm closing this for now. Please reopen if you have a different opinion.
