### ISSUE TITLE
2 Suggestions: Remove assumptions about items and add property lists

### ISSUE THREAD

**Issue by rswgnu** [DamienCassou/hierarchy#63]
Great idea for a library.  I just took a quick look but if you really want to make it a generic library for wide use, I would suggest you abstract the idea of item and add functions that access any needed part of item, e.g. its printed representation, its sortable representation and its property list which I also suggest you add.  Then you'll be on your way to broader generality and use.

**Comment by DamienCassou** [comment]
> Great idea for a library.

thank you.

> I just took a quick look but if you really want to make it a generic library for wide use, I would suggest you abstract the idea of item

an item can already be anything which can be tested for equality with `equal`. Can you give a little more detail about what you would like me to change?

> and add functions that access any needed part of item, e.g. its printed representation, its sortable representation

the printing (`labelfn`) and sorting (`sortfn`) functions are already passed as parameters. What do you want more?

> and its property list which I also suggest you add

can you please tell me more about that? What would API look like?

I've already used the library with lists and cl-structs as hierarchy items.

**Comment by rswgnu** [comment]
On Thu, Oct 19, 2017 at 4:53 AM, Damien Cassou <notifications@github.com>
wrote:

> I just took a quick look but if you really want to make it a generic
> library for wide use, I would suggest you abstract the idea of item
>
> ​I'd like to see more of an object-oriented interface for both hierarchies
and items.  Right now, I see no abstraction for items at all.  Shouldn't
there be a print interface, a display interface, etc. so that if someone
wants to change this, they have one place to go rather than relying on use
of basic Lisp functions.
​
| an item can already be anything which can be tested for equality with
equal. Can you give a little more detail about what you would like me to
change?

Identify and separate what you feel are the public and private interfaces
to hierarchies and items so it is clear to the user.

> ​​
> and add functions that access any needed part of item, e.g. its printed
> representation, its sortable representation
> ​​
>
> ​​
> the printing (labelfn) and sorting (sortfn) functions are already passed
> as parameters. What do you want more?
>
> ​​With that setup, the labelfn and sortfn have to know about the internals
of items in order to operate on them appropriately.  With an item
abstraction, these functions would use the item's interfaces to get what
they need (which still allows for Lisp-style functional processing after
going through the interface).

> ​​
> and its property list which I also suggest you add
> ​​
>
> ​Part of the item abstraction would be a Lisp property list with accessors
and setters.​


> ​​
> can yo
> ​​
> u please tell me more about that? What would API look like?
> ​​
>
> ​hier-item-set-property
hier-item-get-property
hier-item-get-properties​

​- return the plist​

​hier-item-save - make the item and all its properties persistent

Things like that.​​
​​
​​I hope this is a little helpful though I know it is not much detail.
​​
I've al
​​
ready used the library with lists and cl-structs as h
​​
ierarchy items.
​​

Great.  I would just think in terms of creating interfaces (partial
protocol views over the hierarchy abstraction, one per main hierarchy
function: display, printing, mapping, editing) and then name and group your
functions accordingly.

Regards,

Bob

> ​​
>
>

**Comment by DamienCassou** [comment]
What you are proposing seems like an object-oriented based API and implementation. I like the functional style better for this particular project. I'm closing this issue for now as I don't want to drastically change my code. If you have anything more lightweight to propose, please open a new issue.

**Comment by rswgnu** [comment]
On Mon, Oct 23, 2017 at 2:58 AM, Damien Cassou <notifications@github.com>
wrote:

> What you are proposing seems like an object-oriented based API and
> implementation. I like the functional style better for this particular
> project.
>
​I'm really just pushing for greater abstraction and encapsulation which of
course OO provides but which can be done with a functional style as well,
e.g. the whole genesis of the Scheme language.​  Basically, just do a
review of the code and think about how to minimize/localize any knowledge
users of hierarchy would have to have; I have pointed out some aspects of
that.
​​
​| I'm closing this issue for now as I don't want to drastically change my
code. If you have anything more lightweight to propose, please open a new
issue.

Will do.  Thanks for thinking about this.

Bob
