### ISSUE TITLE
Thanks for the mode, using it on my new md4rd (mode-for-reddit) mode!  Quick question about expanding tree...

### ISSUE THREAD

**Issue by ahungry** [DamienCassou/hierarchy#66]
First off, thanks, using it here to great effect (incase you want an example of a more in-depth mode using the facilities you provide):

https://github.com/ahungry/md4rd

Onto the question - is there any way (built in Emacs or via the mode) to quickly expand or close all trees in the currently shown buffer?  Or would I need to write a custom loop/map across all found widgets and simulate clicks on them?

Also - in my code, I had to make a custom function of your labelfn to allow injecting my own 'hook' (post run code, to serve as plain text that shows up *after* the button label is rendered, to give it the threaded comment look).

Would you be interested in adding something in the actual codebase to support user run hooks after each label/button function?

https://github.com/ahungry/md4rd/blob/master/md4rd.el#L398

**Comment by DamienCassou** [comment]
> First off, thanks, using it here to great effect 

I'm happy it can be useful to others. That was the point. How did you like the API? Was it simple to learn and play with?

> is there any way (built in Emacs or via the mode) to quickly expand or close all trees in the currently shown buffer?

I don't know.

> Would you be interested in adding something in the actual codebase to support user run hooks after each label/button function?

I'm not sure I understand what you mean, but feel free to open a PR with a prototype so we can discuss about it.

**Comment by ahungry** [comment]
Turns out `tree-mode` has built in facilities that collapse/expand all tree widgets in the current buffer, and see hierarchy is also using widget-tree, it works perfectly together.

The API was good, I plan to make some other packages that use it as well.

Third point, I'll send up a PR, sure - as it is, the code is fine for a basic hierarchy, but if you want to insert non-button text after a button line (as a description/preview of some content etc.) it doesn't really have built in mechanisms for it (having a hook cycle in each labelfn allows for this).

**Comment by DamienCassou** [comment]
I'm closing this issue as there hasn't been any activity for some time. Feel free to reopen if you want to go back to it.
