### ISSUE TITLE
Feature request: improved navigation

### ISSUE THREAD

**Issue by diamond-lizard** [DamienCassou/hierarchy#68]
I'd like to request the following ways to make navigating hierarchies easier and more convenient.

Please note that for all the movement founctions requested here, the position jumped to should be exactly on the next or previous `[+]`, `[-]` or `[X]`.

1 - Functions to jump to the next or previous node.  `(widget-forward)` and `(widget-backward)` are not quite right for this because they may jump to the current node if point is anywhere other than on the current node's widget.

2 - A function which jumps to the first child of a node (if one exists), unfolding the current node if necessary.

3 - A function which jumps to the parent of the current node.

4 - Functions which jump to the next or previous sibling, skipping its children.

5 - A function which unfolds all the nodes in the current branch.

6 - A function which folds all the nodes in the current branch at and below the current node.

**Comment by DamienCassou** [comment]
`hierarchy` is not doing much to represent trees, it just uses the Emacs widget. If you have suggestions to improve the widget, you may want to ask the Emacs mailing list instead. Another solution would be to create a dedicated Emacs package. Then. `hierarchy` could use that.

**Comment by DamienCassou** [comment]
I'm closing this for now. Please reopen if you have a different opinion.
