### ISSUE TITLE
Feature request: major mode for hierarchy-tree buffers

### ISSUE THREAD

**Issue by diamond-lizard** [DamienCassou/hierarchy#69]
I'd like to request that hierachy-tree buffers have their own major mode, so that the user could bind hierarchy-related functions to keys in that mode

**Comment by DamienCassou** [comment]
The target users of `hierarchy` are library authors and I expect them to have their own major mode. The function `hierarchy-tree-display` is mostly a demo to show how people could render a hierarchy with a tree widget. I don't plan to give that function more responsibility for now.

**Comment by DamienCassou** [comment]
I'm closing this for now. Please reopen if you have a different opinion.
