### ISSUE TITLE
The hierarchy view reverses contents of arrays

### ISSUE THREAD

**Issue by ndokos** [DamienCassou/hierarchy#71]
Consider a JSON document like this:

````
[
  {
    "params": {
      "test": [
        "foo",
        "bar"
      ]
    }
  }
]
````
Doing `M-x json-navigator-navigate-after-point` and unfolding up to and including the "test" nodes shows an array `[foo, bar]`, but unfolding that gives two leaf nodes in the reverse order: first "bar" and then "foo".

**Comment by DamienCassou** [comment]
Closed by #70.
