### ISSUE TITLE
[[Inquery]] Have the Widget of Leafs Display as Closed and Attach Actions to Widgets

### ISSUE THREAD

**Issue by WammKD** [DamienCassou/hierarchy#72]
Just curious if it'd be feasible but, for readability/parsing at a glance, would it be possible to set the type of widget for the `hierarchy-tree-display` function or, barring that, have all leafs indicate in their icon that they have no children (like in this image of JDIbug: http://www.skybert.net/graphics/emacs/jdibug_remote_debugging_browsing_the_call_stack.png).

Additionally, I don't know if it's possible to attach actions to widgets but, if so, would it be possible to set actions for the widgets via `hierarchy-tree-display`?

Either way, thanks a ton!

**Comment by DamienCassou** [comment]
I have no clue and I'm investing my time somewhere else. You can investigate and send PRs if you want to.

**Comment by WammKD** [comment]
Well, the widget documentation doesn't seem to help me, any. Seems there's different icons for different states (opened, closed, etc.) including a "leaf" state so, in theory, it'd take care of itself. Oh well; 'twas the least import part.

In terms of triggering actions, I don't seem to see any way to do it, which kinda surprises me, and I've never seen an example of it done, when I think about it.

A work around is inserting a text button for the tag of the widget and calling that but it highlights every word/node.

Oh well; 'gonna close this, for now, based off of the above and I can always round back and submit a PR or something if I find any new info.

Thanks, again!
